// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOVJ4QFC-vhCHKEHmaaqc2PUPYJl5mVrg',
    appId: '1:99850291815:web:29e05917c11765b00d22c2',
    messagingSenderId: '99850291815',
    projectId: 'cleanmind-344d2',
    authDomain: 'cleanmind-344d2.firebaseapp.com',
    storageBucket: 'cleanmind-344d2.firebasestorage.app',
    measurementId: 'G-3JF2H0BQ53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJsqPLvfh-4tC2zV5Uf4kCQ7Zs_WXx1k',
    appId: '1:99850291815:android:89808d74cc2d010a0d22c2',
    messagingSenderId: '99850291815',
    projectId: 'cleanmind-344d2',
    storageBucket: 'cleanmind-344d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjcXUCHKQ6zi9jFUizizc9Ebf0qNl3Qc',
    appId: '1:99850291815:ios:ef967da51d751f360d22c2',
    messagingSenderId: '99850291815',
    projectId: 'onlymens-344d2',
    storageBucket: 'onlymens-344d2.firebasestorage.app',
    androidClientId: '99850291815-r5thu3jolbvv3nf3q8t5edvr8vabpm61.apps.googleusercontent.com',
    iosClientId: '99850291815-nlhlh5jgg7rvsagev5ac8ii7p2t16oco.apps.googleusercontent.com',
    iosBundleId: 'com.sakib.onlymens',
  );

}